languageCode: "en-us"
baseUrl: "https://kalverra.github.io/"
# baseUrl: "http://localhost:1313/"
title: "Adam's Writing Thing"
theme: "anubis"
paginate: 15
enableRobotsTXT: true
googleAnalytics: G-76ECS8F1DQ
enableEmoji: true

menu:
  main:
    - identifier: all
      name: All
      title: All
      url: /
      weight: 1
    - identifier: essays
      name: Essays
      title: Essays
      url: /essays/
      weight: 2
    - identifier: tech-explainers
      name: Tech Explainers
      title: Tech Explainers
      url: /tech-explainers/
      weight: 3
    - identifier: programming
      name: Programming
      title: Programming
      url: /programming/
      weight: 4
    - identifier: books
      name: Books
      title: Books
      url: /books/
      weight: 5
    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 98
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 99

taxonomies:
  category: categories
  tag: tags

params:
  author: "Adam Hamrick"
  avatar: "/images/head_shot.jpeg" # used for microformats
  description: ""
  disableSummary: false
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: auto
  readMore: false
  copyCodeButton: true
  rssAsSocialIcon: true
  social:
    - id: github
      name: kalverra
    - id: linkedin
      name: adam-hamrick-8b1866116
  mainSections:
    - essays
    - programming
    - tech-explainers
    - books

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
